module.exports = {
  number: 21,
  route: '/become/practice-change/',
  stage: 'Become',
  title: 'Listen Deeply — Relationship Is Interactive',
  eyebrow: 'BECOMING  •  PART ONE  •  LESSON 2 OF 6  •  SCREEN 1 OF 2',
  lesson: 2,
  screen: 1,
  previous: { label: 'PREVIOUS: RECOGNIZE HIS PRESENCE', href: '/become/living-from-love/' },
  next: { label: 'NEXT: SCREEN 2', href: '/become/rule-of-life/' },
  content: [
    { className: 'p21-intro', blocks: [
      { type: 'lead', text: 'God did not invite you into a relationship in which He does all the listening.' },
      { type: 'p', text: 'Many of us have learned a version of relationship with God that is strangely one-directional.' },
      { type: 'p', text: 'We speak to Him in prayer. We read what He said in Scripture. We worship Him. We ask for guidance. We try to obey what we already know.' },
      { type: 'p', text: 'All of those things matter. But Jesus describes something more interactive.' },
      { type: 'p', text: 'He lived with continual awareness of the Father. He watched for what the Father was doing. He listened. He responded. His actions flowed from relationship rather than from independently deciding what ought to be done for God.' },
      { type: 'callout', text: 'What if following Jesus means learning not only what He taught, but learning the kind of relationship with the Father from which He lived?' },
    ] },
    { className: 'p21-scripture', blocks: [
      { type: 'heading', text: 'JESUS DIDN’T MERELY BELIEVE IN THE FATHER. HE LIVED RESPONSIVELY TO HIM.' },
      { type: 'scripture', text: '“The Son can do nothing by himself; he can do only what he sees his Father doing.”', cite: '— JOHN 5:19' },
      { type: 'p', text: 'Jesus was not describing passivity. He was describing dependence. He did not simply determine the best course of action and ask the Father to support it.' },
      { type: 'rule' },
      { type: 'p', text: 'That changes the question from:' },
      { type: 'strong', text: '“God, what do You want me to accomplish for You?”' },
      { type: 'p', text: 'to:' },
      { type: 'accent', text: '“Father, what are You doing, and what is mine to do with You?”' },
      { type: 'p', text: 'That question will eventually lead us into Join, but learning to live this way begins here.' },
    ] },
    { className: 'p21-prayer', blocks: [
      { type: 'heading', text: 'PRAYER BECOMES CONVERSATION' },
      { type: 'p', text: 'Prayer certainly includes speaking. But relationship cannot mature if we assume communication only travels in one direction. So we begin asking different questions:' },
      { type: 'list', columns: 2, items: ['Father, what are You doing?', 'What do You want me to see?', 'Is there something here I am not understanding?', 'What are You showing me about myself?', 'Is there something You want me to do?', 'Is there something You want me to leave alone?'] },
      { type: 'p', text: 'And then comes the part many of us have never learned:' },
      { type: 'accent', text: 'We stop talking long enough to pay attention.' },
    ] },
    { className: 'p21-listening', blocks: [
      { type: 'heading', text: 'LISTENING IS NOT STRAINING TO HEAR' },
      { type: 'p', text: 'This distinction is essential.' },
      { type: 'p', text: 'Listening isn’t trying harder to hear a voice.' },
      { type: 'accent', text: 'It is becoming attentive to a God who is already communicating.' },
      { type: 'p', text: 'A thought may come. A Scripture may suddenly illuminate something. Something another person says may expose what we couldn’t see. There may be conviction. A question may remain with us. Something may become unusually clear. Or there may simply be silence.' },
      { type: 'gold', text: 'We do not have to immediately label any of these things “God said.”' },
      { type: 'p', text: 'We notice. We remain with Him. We learn. And over time, we become increasingly familiar with Him.' },
    ] },
    { className: 'p21-shift', blocks: [
      { type: 'heading', text: 'THE SHIFT' },
      { type: 'p', text: 'Immature listening asks:' },
      { type: 'iconCallout', icon: 'ear.svg', text: 'How do I get God to tell me what to do?' },
      { type: 'p', text: 'Maturing relationship asks:' },
      { type: 'iconCallout', icon: 'heart.svg', text: 'How do I become so familiar with God that I increasingly recognize His activity, His character, His direction, and His invitations?' },
      { type: 'rule' },
      { type: 'p', text: 'We are not learning a technique for getting answers.' },
      { type: 'accent', text: 'We are becoming the kind of person who lives attentively with God.' },
    ] },
  ],
};
