const ASSET_ROOT = '/assets/page-ranges/range-36-40';

const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[character]));

const icon = (name, label = '') => `<svg class="rts-36-40__icon"${label ? ` role="img" aria-label="${escapeHtml(label)}"` : ' aria-hidden="true"'}><use href="${ASSET_ROOT}/icons.svg#${escapeHtml(name)}"></use></svg>`;

function brand(mark = 'tree') {
  return `<a class="rts-36-40__brand" href="/" aria-label="Reforming the Soul home"><img src="${ASSET_ROOT}/${mark === 'tree' ? 'brand-tree.svg' : 'brand-crescent.svg'}" alt=""><span>Reforming<em>the Soul</em></span></a>`;
}

function formationHeader(page, active = page.stage, auxiliary = []) {
  if (page.number === 38 && auxiliary.length === 0) auxiliary = [{ label: 'Conversations', href: '/conversations/', active: true }];
  return `<header class="rts-36-40__header">${brand(page.number === 38 ? 'crescent' : 'tree')}<nav aria-label="Formation stages and resources">${page.stages.map(stage => `<a data-stage="${escapeHtml(stage.name)}" class="${stage.name === active ? 'is-active' : ''}" href="${stage.href}">${escapeHtml(stage.name)}</a>`).join('')}${auxiliary.map(item => `<a class="${item.active ? 'is-active' : ''}" href="${item.href}">${escapeHtml(item.label)}</a>`).join('')}</nav><a class="rts-36-40__header-cta" href="/conversations/">Enter a conversation</a><span class="rts-36-40__account" aria-label="Account">${icon('person')}</span></header>`;
}

function journeyRail(page, { progress, support, activeStage = page.number === 38 ? '' : page.stage } = {}) {
  if (page.number === 38) progress = null;
  return `<aside class="rts-36-40__rail" aria-label="The formation journey"><h2>The Formation Journey</h2><ol>${page.stages.map(stage => `<li class="${stage.name === activeStage ? 'is-active' : ''}"><a data-stage="${escapeHtml(stage.name)}" href="${stage.href}">${icon(stage.icon)}<span><strong>${escapeHtml(stage.name)}</strong><small>${escapeHtml(stage.description)}</small></span></a></li>`).join('')}</ol>${progress ? `<section class="rts-36-40__progress"><h3>Your progress</h3><p><span>${escapeHtml(progress.label)}</span><span>${escapeHtml(progress.count)}</span></p><progress max="${progress.max}" value="${progress.value}">${escapeHtml(progress.count)}</progress></section>` : ''}${support ? `<section class="rts-36-40__support"><h3>${icon('help')}${escapeHtml(support.heading)}</h3><p>${escapeHtml(support.copy)}</p><a href="${support.href}">${escapeHtml(support.label)} <span aria-hidden="true">→</span></a></section>` : ''}</aside>`;
}

function stageBar(page) {
  return `<div class="rts-36-40__stage-bar"><strong>The Formation Journey</strong><nav aria-label="Journey progress">${page.stages.map(stage => `<a data-stage="${escapeHtml(stage.name)}" class="${stage.name === page.stage ? 'is-active' : ''}" href="${stage.href}">${icon(stage.icon)}<span>${escapeHtml(stage.name)}</span>${stage.name !== page.stage ? '<b aria-hidden="true">✓</b>' : ''}</a>`).join('')}</nav></div>`;
}

function render36(page) {
  return `<div class="rts-36-40 rts-36-40--p36">${formationHeader(page)}<div class="rts-36-40__course-shell">${journeyRail(page, { support: { heading: 'Need help?', copy: 'We’re here if you have questions along the way.', label: 'Contact Support', href: '/coming-soon/' } })}<main class="rts-36-40__changed-person"><header class="rts-36-40__changed-intro"><p class="rts-36-40__trail">${page.trail.map(escapeHtml).join(' <span>•</span> ')}</p><h1>${escapeHtml(page.heading)}</h1><p>${escapeHtml(page.introduction)}</p><strong>${escapeHtml(page.emphasis)}</strong></header><figure class="rts-36-40__changed-scene" data-raster-slot="p36-sunset-portrait"><div class="rts-36-40__portrait-silhouette" aria-hidden="true"></div><blockquote><span aria-hidden="true">“</span>${escapeHtml(page.quote.copy)}<cite>— ${escapeHtml(page.quote.reference)}</cite></blockquote></figure><section class="rts-36-40__domain-grid" aria-label="Characteristics of a changed person">${page.domains.map((domain, index) => `<article class="rts-36-40__domain rts-36-40__domain--${domain.tone}"><header>${icon(domain.icon)}<h2>${escapeHtml(domain.title)}</h2></header><div class="rts-36-40__domain-photo rts-36-40__domain-photo--${index + 1}" data-raster-slot="p36-domain-${index + 1}" role="img" aria-label="Replaceable editorial portrait for ${escapeHtml(domain.title.toLowerCase())}"></div>${domain.paragraphs.map(copy => `<p>${escapeHtml(copy)}</p>`).join('')}<p class="rts-36-40__evidence"><strong>Evidence of change:</strong>${escapeHtml(domain.evidence)}</p></article>`).join('')}</section><nav class="rts-36-40__pagination" aria-label="Lesson screens"><a href="${page.pagination.previous.href}">← ${escapeHtml(page.pagination.previous.label)}</a><ol>${Array.from({ length: page.pagination.total }, (_, index) => `<li class="${index + 1 === page.pagination.current ? 'is-current' : ''}">${index + 1}</li>`).join('')}</ol><a href="${page.pagination.next.href}">${escapeHtml(page.pagination.next.label)} →</a></nav></main></div></div>`;
}

function render37(page) {
  const movement = entry => `<article class="rts-36-40__movement rts-36-40__movement--${entry.tone}"><header>${icon(entry.icon)}<h2>${escapeHtml(entry.title)}</h2></header><div class="rts-36-40__movement-body"><div>${entry.paragraphs ? entry.paragraphs.map(copy => `<p>${escapeHtml(copy)}</p>`).join('') : ''}${entry.bullets ? `<ul>${entry.bullets.map(copy => `<li>${icon('check')}${escapeHtml(copy)}</li>`).join('')}</ul>` : ''}${entry.questions ? `<ul class="rts-36-40__questions">${entry.questions.map(copy => `<li>→ ${escapeHtml(copy)}</li>`).join('')}</ul>` : ''}</div><p class="rts-36-40__movement-aside">${escapeHtml(entry.aside)}</p></div></article>`;
  return `<div class="rts-36-40 rts-36-40--p37">${formationHeader(page)}${stageBar(page)}<main class="rts-36-40__join-page"><section class="rts-36-40__join-hero"><div><h1><span>${escapeHtml(page.headingLines[0])}</span><em>${escapeHtml(page.headingLines[1])}</em></h1><span class="rts-36-40__rule"></span>${page.introduction.map((copy, index) => `<p class="${index ? 'is-emphasis' : ''}">${escapeHtml(copy)}</p>`).join('')}${page.summary.map((copy, index) => `<p class="${index ? 'is-emphasis' : ''}">${escapeHtml(copy)}</p>`).join('')}</div><figure data-raster-slot="p37-community-overlook" aria-label="Replaceable photograph of four people overlooking a mountain valley"><div class="rts-36-40__community-silhouettes" aria-hidden="true"><span></span><span></span><span></span><span></span></div></figure></section><section class="rts-36-40__movements" aria-label="A restored life">${page.movements.map(movement).join('')}</section><section class="rts-36-40__declaration">${icon('cross')}<p>${escapeHtml(page.declaration)}</p><blockquote>${escapeHtml(page.quote.copy)}<cite>— ${escapeHtml(page.quote.reference)}</cite></blockquote></section></main><footer class="rts-36-40__journey-closing"><strong>${escapeHtml(page.closing.heading)}</strong><span>${escapeHtml(page.closing.copy)}</span></footer></div>`;
}

function render38(page) {
  return `<div class="rts-36-40 rts-36-40--p38">${formationHeader(page, '')}<div class="rts-36-40__conversation-shell">${journeyRail(page, { progress: { label: 'Conversations', count: '1 of 1', max: 1, value: 1 }, support: page.support })}<main class="rts-36-40__conversation-page"><section class="rts-36-40__conversation-copy"><p class="rts-36-40__eyebrow">${icon('leaf')}${escapeHtml(page.eyebrow)}</p><h1>${escapeHtml(page.heading)}</h1><span class="rts-36-40__rule"></span><h2>${escapeHtml(page.headline)}</h2><p>${escapeHtml(page.introduction)}</p><a class="rts-36-40__booking" href="${page.booking.href}">${icon('calendar')}<span><strong>${escapeHtml(page.booking.label)}</strong><small>${escapeHtml(page.booking.detail)}</small></span><b aria-hidden="true">→</b></a><section class="rts-36-40__benefits" aria-label="Conversation qualities">${page.benefits.map(benefit => `<article>${icon(benefit.icon)}<h3>${escapeHtml(benefit.title)}</h3><p>${escapeHtml(benefit.copy)}</p></article>`).join('')}</section></section><figure class="rts-36-40__conversation-scene" data-raster-slot="p38-chairs-overlook"><div class="rts-36-40__chairs" aria-hidden="true"><span></span><span></span></div><aside class="rts-36-40__principles"><header>${icon('leaf')}<h2>A different kind<br>of conversation</h2></header>${page.principles.map(principle => `<div>${icon(principle.icon)}<p>${escapeHtml(principle.copy)}</p></div>`).join('')}</aside></figure></main></div><section class="rts-36-40__scripture"><blockquote><span aria-hidden="true">“</span>${escapeHtml(page.scripture)}<cite>— ${escapeHtml(page.scriptureReference)}</cite></blockquote></section></div>`;
}

function editorialHeader(page, mark) {
  const hrefs = { Teachings: '/coming-soon/', Writings: '/coming-soon/', Books: '/books/', Music: '/music/', 'Spiritual Direction': '/conversations/', 'About Us': '/coming-soon/' };
  return `<header class="rts-36-40__editorial-header">${brand(mark)}<nav aria-label="Main navigation">${page.nav.map(item => `<a class="${item === page.title ? 'is-active' : ''}" href="${hrefs[item]}">${escapeHtml(item)}</a>`).join('')}</nav><a class="rts-36-40__start" href="/awaken/">Start here</a></header>`;
}

function render39(page) {
  const columns = [page.songs.slice(0, 10), page.songs.slice(10, 18), page.songs.slice(18, 26), page.songs.slice(26, 34), page.songs.slice(34)];
  return `<div class="rts-36-40 rts-36-40--p39">${editorialHeader(page, 'crescent')}<main class="rts-36-40__music-page"><section class="rts-36-40__music-hero" data-raster-slot="p39-alluminate-valley"><div class="rts-36-40__music-copy"><h1>${escapeHtml(page.heading)}</h1><p class="rts-36-40__music-tagline">${page.tagline.map(escapeHtml).join('<br>')}</p>${page.introduction.map(copy => `<p>${escapeHtml(copy)}</p>`).join('')}<a href="${page.primaryAction.href}">${icon('play')}${escapeHtml(page.primaryAction.label)}</a></div><blockquote><span aria-hidden="true">“</span>${escapeHtml(page.quote)}</blockquote></section><section class="rts-36-40__song-library"><h2>Select a song to listen</h2><div class="rts-36-40__song-columns">${columns.map(column => `<ul>${column.map(song => `<li><button type="button" aria-label="Play ${escapeHtml(song)}">${icon('play')}</button>${escapeHtml(song)}</li>`).join('')}</ul>`).join('')}<aside>${icon('headphones')}<p>${escapeHtml(page.card.heading)}</p><a href="/coming-soon/">${escapeHtml(page.card.action)}</a></aside></div></section></main><footer class="rts-36-40__music-closing"><h2>${escapeHtml(page.closing.heading)}</h2><nav aria-label="Music themes">${page.closing.pillars.map((pillar, index) => `<span>${icon(['see', 'heart', 'music'][index])}${escapeHtml(pillar)}</span>`).join('')}</nav></footer></div>`;
}

function render40(page) {
  return `<div class="rts-36-40 rts-36-40--p40">${editorialHeader(page, 'crescent')}<main class="rts-36-40__books-page"><section class="rts-36-40__books-hero" data-raster-slot="p40-books-mountain-table"><div><h1>${page.headingLines.map((line, index) => `<${index ? 'em' : 'span'}>${escapeHtml(line)}</${index ? 'em' : 'span'}>`).join('')} </h1><span class="rts-36-40__rule"></span>${page.introduction.map(copy => `<p>${escapeHtml(copy)}</p>`).join('')}<a href="${page.primaryAction.href}">${icon('book')}${escapeHtml(page.primaryAction.label)}</a></div><blockquote><span aria-hidden="true">“</span>${escapeHtml(page.quote)}</blockquote><div class="rts-36-40__book-stack" aria-hidden="true"><i></i><i></i><i></i></div></section><section id="range-36-40-books" class="rts-36-40__book-library"><h2>Explore Our Books</h2><div class="rts-36-40__book-grid">${page.books.map((book, index) => `<article class="rts-36-40__cover" data-raster-slot="p40-cover-${index + 1}"><img src="${ASSET_ROOT}/fidelity/page-40-cover-${String(index + 1).padStart(2, '0')}.jpg" alt="${escapeHtml(book)} book cover"></article>`).join('')}<aside>${icon('book')}<p>${escapeHtml(page.card.heading)}</p><a href="/coming-soon/">${escapeHtml(page.card.action)}</a></aside></div></section></main><footer class="rts-36-40__books-closing"><h2>${escapeHtml(page.closing.heading)}</h2><strong>${escapeHtml(page.closing.subheading)}</strong><blockquote>${escapeHtml(page.closing.quote)}</blockquote></footer></div>`;
}

const renderers = new Map([[36, render36], [37, render37], [38, render38], [39, render39], [40, render40]]);

module.exports = function render(page) {
  const renderer = page && renderers.get(page.number);
  if (!renderer) throw new RangeError('Only Pages 36–40 are supported by this renderer.');
  return renderer(page);
};
