const lessons = [
  [1,"Soul Formation","/","Awaken","hero","A journey toward wholeness","Your soul is always being formed. Choose a path of attentive, honest transformation."],
  [2,"Awaken","/awaken/","Awaken","stage","Notice what is stirring","Awakening begins when we become present to God, ourselves, and the stories shaping our lives."],
  [3,"Pay Attention","/awaken/pay-attention/","Awaken","lesson","The invitation to notice","Slow down long enough to recognize what is happening within and around you."],
  [4,"Name Your Desire","/awaken/name-your-desire/","Awaken","lesson","What do you truly want?","Desire can become a doorway to honest prayer and deeper freedom."],
  [5,"Listen Within","/awaken/listen-within/","Awaken","reflection","Make room for your soul","Practice listening without judgment, hurry, or the need to manufacture an answer."],
  [6,"A Practice of Presence","/awaken/practice-presence/","Awaken","practice","Be here now","A simple practice for returning to the present with openness and compassion."],
  [7,"See Clearly I","/see-clearly/","See Clearly","stage","Understand your story","Clarity grows as we learn to see the forces that have formed us."],
  [8,"Your Formation","/see-clearly/your-formation/","See Clearly","lesson","We are all being formed","Explore the people, places, patterns, and experiences that have shaped your inner life."],
  [9,"Family of Origin","/see-clearly/family-of-origin/","See Clearly","lesson","The story behind the story","Attend to your family story with courage, curiosity, and grace."],
  [10,"Patterns and Protection","/see-clearly/patterns/","See Clearly","lesson","What once kept you safe","Recognize protective patterns and consider what they offer—and what they cost."],
  [11,"The False Self","/see-clearly/false-self/","See Clearly","reflection","Release what is not true","Notice the identities we construct to secure love, belonging, and control."],
  [12,"Reflection and Review","/see-clearly/review-one/","See Clearly","practice","Pause and gather","Bring the movements of this part of your journey together in reflection."],
  [13,"See God Clearly","/see-god-clearly/","See Clearly","stage","Receive a truer image","How we imagine God profoundly shapes how we live, love, and become."],
  [14,"Images of God","/see-god-clearly/images/","See Clearly","lesson","What picture do you carry?","Explore the images and assumptions that influence your relationship with God."],
  [15,"Distorted Images","/see-god-clearly/distortions/","See Clearly","lesson","When fear shapes faith","Gently identify images of God that diminish trust, freedom, or love."],
  [16,"God With Us","/see-god-clearly/with-us/","See Clearly","reflection","Nearer than we know","Consider a God who is present, loving, and active in the reality of your life."],
  [17,"Reflection and Practice","/see-god-clearly/practice/","See Clearly","practice","Rest in belovedness","A guided pause for receiving a more spacious and loving vision of God."],
  [18,"Become","/become/","Become","stage","Live from your true self","Transformation becomes embodied through practice, relationship, and courageous choice."],
  [19,"The True Self","/become/true-self/","Become","lesson","Become who you already are","The true self is received rather than achieved—a life rooted in love."],
  [20,"Living from Love","/become/living-from-love/","Become","reflection","A different center","Explore the freedom of responding from love rather than fear."],
  [21,"Practice and Change","/become/practice-change/","Become","lesson","Small choices shape a life","Lasting formation grows through ordinary, repeated practices."],
  [22,"Rule of Life","/become/rule-of-life/","Become","workbook","A trellis for growth","Create a flexible rhythm that supports the life you are being invited to live."],
  [23,"Relationships","/become/relationships/","Become","lesson","We become together","Healthy formation takes place in relationships marked by truth and grace."],
  [24,"Boundaries","/become/boundaries/","Become","reflection","Love with clarity","Boundaries help us honor our limits and remain present with integrity."],
  [25,"Repair","/become/repair/","Become","lesson","The courage to return","Learn practices of confession, repair, forgiveness, and renewed connection."],
  [26,"Embodied Faith","/become/embodied-faith/","Become","lesson","Honor the whole person","Attend to the body as an essential companion in spiritual formation."],
  [27,"Daily Examen","/become/daily-examen/","Become","practice","Notice the day with God","A repeatable practice of gratitude, honesty, and discernment."],
  [28,"Integrating the Journey","/become/integrate/","Become","reflection","Gather what is changing","Name what you are learning and how you hope to carry it forward."],
  [29,"A Closing Blessing","/become/blessing/","Become","closing","Go in wholeness","Receive a blessing for the path ahead and the person you are becoming."],
  [30,"Become Together","/become-together/","Become","stage","Transformation in community","Deep change is sustained when we practice honesty, presence, and love together."],
  [31,"Sacred Companions","/become-together/companions/","Become","lesson","Do not journey alone","Discover the gift of people who listen well and tell the truth in love."],
  [32,"Listening Well","/become-together/listening/","Become","lesson","Offer the gift of presence","Practice listening with curiosity, restraint, and care."],
  [33,"Creating Safety","/become-together/safety/","Become","lesson","Make room for honesty","Cultivate spaces where people can be known without being managed."],
  [34,"Shared Practice","/become-together/shared-practice/","Become","practice","A rhythm for groups","Use a simple shared practice to deepen attention and connection."],
  [35,"Guided Conversation","/become-together/guided-conversation/","Become","workbook","Questions that open space","Conversation prompts for reflecting on formation with trusted people."],
  [36,"Sending Practice","/become-together/sending/","Become","closing","Carry it together","Mark the end of this movement and the beginning of faithful practice."],
  [37,"Join the Journey","/join/","Join","cta","Find your next step","Explore ways to learn, participate, give, and stay connected with Reforming the Soul."],
  [38,"Conversations","/conversations/","Join","library","Stories worth sharing","Thoughtful conversations about life with God, emotional health, and spiritual formation."],
  [39,"Music","/music/","Join","library","Songs for the journey","A curated place for music that helps us attend, remember, and respond."],
  [40,"Books","/books/","Join","library","Read more deeply","Recommended books for a life of honest, relational spiritual formation."]
];
module.exports = lessons.map(([number,title,route,stage,template,eyebrow,summary])=>({number,title,route,stage,template,eyebrow,summary}));
