const lessons = [
  [0,"RTS Home Page","/","Reforming the Soul","home","You’re being shaped by something","The main Reforming the Soul landing page."],
  [1,"Soul Formation","/soul-formation/","Awaken","hero","A journey toward wholeness","Your soul is always being formed. Choose a path of attentive, honest transformation."],
  [2,"You Have Already Been Formed","/awaken/","Awaken","stage","Notice what is stirring","Awakening begins when we become present to God, ourselves, and the stories shaping our lives."],
  [3,"Where Did That Come From?","/awaken/pay-attention/","Awaken","lesson","The invitation to notice","Slow down long enough to recognize what is happening within and around you."],
  [4,"Look Beneath the Surface","/awaken/name-your-desire/","Awaken","lesson","What do you truly want?","Desire can become a doorway to honest prayer and deeper freedom."],
  [5,"God Already Sees It","/awaken/listen-within/","Awaken","reflection","Make room for your soul","Practice listening without judgment, hurry, or the need to manufacture an answer."],
  [6,"Catch Yourself Being You","/awaken/practice-presence/","Awaken","practice","Be here now","A simple practice for returning to the present with openness and compassion."],
  [7,"See Who You Really Are","/see-clearly/","See Clearly","stage","Understand your story","Clarity grows as we learn to see the forces that have formed us."],
  [8,"Who Are You Now?","/see-clearly/your-formation/","See Clearly","lesson","We are all being formed","Explore the people, places, patterns, and experiences that have shaped your inner life."],
  [9,"What Actually Happened?","/see-clearly/family-of-origin/","See Clearly","lesson","The story behind the story","Attend to your family story with courage, curiosity, and grace."],
  [10,"What Are You Still Living From?","/see-clearly/patterns/","See Clearly","lesson","What once kept you safe","Recognize protective patterns and consider what they offer—and what they cost."],
  [11,"That’s Formation, Not Identity","/see-clearly/false-self/","See Clearly","reflection","Release what is not true","Notice the identities we construct to secure love, belonging, and control."],
  [12,"Make Room for Life","/see-clearly/review-one/","See Clearly","practice","Pause and gather","Bring the movements of this part of your journey together in reflection."],
  [13,"Seeing God Clearly","/see-god-clearly/","See Clearly","stage","Receive a truer image","How we imagine God profoundly shapes how we live, love, and become."],
  [14,"Is This God Trustworthy?","/see-god-clearly/images/","See Clearly","lesson","What picture do you carry?","Explore the images and assumptions that influence your relationship with God."],
  [15,"The Same God.","/see-god-clearly/distortions/","See Clearly","lesson","When fear shapes faith","Gently identify images of God that diminish trust, freedom, or love."],
  [16,"What About God’s Anger?","/see-god-clearly/with-us/","See Clearly","reflection","Nearer than we know","Consider a God who is present, loving, and active in the reality of your life."],
  [17,"Look Again.","/see-god-clearly/practice/","See Clearly","practice","Rest in belovedness","A guided pause for receiving a more spacious and loving vision of God."],
  [18,"Becoming","/become/","Become","stage","Live from your true self","Transformation becomes embodied through practice, relationship, and courageous choice."],
  [19,"Recognize His Presence","/become/true-self/","Become","lesson","Become who you already are","The true self is received rather than achieved—a life rooted in love."],
  [20,"Learn to Live From His Presence","/become/living-from-love/","Become","reflection","A different center","Explore the freedom of responding from love rather than fear."],
  [21,"Listen Deeply — Relationship Is Interactive","/become/practice-change/","Become","lesson","Small choices shape a life","Lasting formation grows through ordinary, repeated practices."],
  [22,"Learn to Recognize His Voice","/become/rule-of-life/","Become","workbook","A trellis for growth","Create a flexible rhythm that supports the life you are being invited to live."],
  [23,"Release Control — Whole Surrender to God and His Will","/become/relationships/","Become","lesson","We become together","Healthy formation takes place in relationships marked by truth and grace."],
  [24,"Living With Open Hands","/become/boundaries/","Become","reflection","Love with clarity","Boundaries help us honor our limits and remain present with integrity."],
  [25,"This Is the Moment You Have Been Given","/become/repair/","Become","lesson","The courage to return","Learn practices of confession, repair, forgiveness, and renewed connection."],
  [26,"Even This Moment","/become/embodied-faith/","Become","lesson","Honor the whole person","Attend to the body as an essential companion in spiritual formation."],
  [27,"Even Here, God Is Forming Me","/become/daily-examen/","Become","practice","Notice the day with God","A repeatable practice of gratitude, honesty, and discernment."],
  [28,"What Is Mine to Do?","/become/integrate/","Become","reflection","Gather what is changing","Name what you are learning and how you hope to carry it forward."],
  [29,"From Devotion, Not Duty","/become/blessing/","Become","closing","Go in wholeness","Receive a blessing for the path ahead and the person you are becoming."],
  [30,"Become Through Life With God","/become-together/","Become","stage","Transformation in community","Deep change is sustained when we practice honesty, presence, and love together."],
  [31,"The Will","/become-together/companions/","Become","lesson","Do not journey alone","Discover the gift of people who listen well and tell the truth in love."],
  [32,"The Body","/become-together/listening/","Become","lesson","Offer the gift of presence","Practice listening with curiosity, restraint, and care."],
  [33,"Relationships","/become-together/safety/","Become","lesson","Make room for honesty","Cultivate spaces where people can be known without being managed."],
  [34,"The Soul","/become-together/shared-practice/","Become","practice","A rhythm for groups","Use a simple shared practice to deepen attention and connection."],
  [35,"You Will Know the Tree by Its Fruit","/become-together/guided-conversation/","Become","workbook","Questions that open space","Conversation prompts for reflecting on formation with trusted people."],
  [36,"What a Changed Person Actually Looks Like","/become-together/sending/","Become","closing","Carry it together","Mark the end of this movement and the beginning of faithful practice."],
  [37,"Reformed Souls for His purposes.","/join/","Join","cta","Find your next step","Explore ways to learn, participate, give, and stay connected with Reforming the Soul."],
  [38,"Conversations","/conversations/","Join","library","Stories worth sharing","Thoughtful conversations about life with God, emotional health, and spiritual formation."],
  [39,"Music","/music/","Join","library","Songs for the journey","A curated place for music that helps us attend, remember, and respond."],
  [40,"Books","/books/","Join","library","Read more deeply","Recommended books for a life of honest, relational spiritual formation."]
];
module.exports = lessons.map(([number,title,route,stage,template,eyebrow,summary])=>({number,title,route,stage,template,eyebrow,summary}));
